# **Mini Project : Pengambilan dan Pembersihan Data Melalui API** 

### Pengambilan dan Eksplorasi Data TV Series Menggunakan TMDB API



**Nama**  Muhammad Amar Primus Firdaus

**Program**  AI Automation Engineer

**Project**  Pengambilan dan Pembersihan Data Melalui API



## **Tahap 1: Mendapatkan API Key yang akan digunakan** 

Pada tahap ini, kita membutuhkan API Key untuk dapat mengakses data dari The Movie Database (TMDB) API. API Key berfungsi sebagai kredensial untuk mengautentikasi setiap permintaan yang dikirimkan ke API TMDB.

Setelah mendapatkan API Key, key tersebut disimpan dalam file **.env** agar tidak dituliskan secara langsung di dalam kode program.

In [1]:
# Menginstall library yang dibutuhkan dalam mengakses API
!pip install requests python-dotenv --quiet

In [2]:
# Mengimport library yang dibutuhkan dalam mengaskes API
import requests
import pandas as pd
import time
import os
from dotenv import load_dotenv

# Membaca isi file .env
load_dotenv()  

API_KEY = os.getenv("API_KEY")

if API_KEY:
    print("API key berhasil dimuat.")
else:
    print("API key belum ketemu. Pastikan file .env sudah dibuat dan diisi dengan benar.")

API key berhasil dimuat.

## **Tahap 2: Melakukan pemanggilan pada API**

TMDB punya beberapa alamat (disebut endpoint) untuk mengakses jenis data yang berbeda. Kita akan menggunakan endpoint bernama discover/tv untuk mendapatkan daftar serial TV.

Dengan params sebagai berikut :
1. api_key : kartu identitas untuk mengakses API TMDB
2. language : bahasa data yang ingin ditampilkan
3. page : nomor halaman data yang ingin diambil
4. sort_by : cara mengurutkan data, misalnya berdasarkan popularitas

In [3]:
# Meminta data serial televisi dari TMDB API berdasarkan tingkat popularitas, menggunakan API key, 
# bahasa Inggris, dan halaman pertama, kemudian menampilkan status respons serta jumlah data yang diperoleh.
alamat_api = "https://api.themoviedb.org/3/discover/tv"

parameter = {
    "api_key"  : API_KEY,
    "language" : "en-US",
    "page"     : 1,
    "sort_by"  : "popularity.desc"
}

response = requests.get(alamat_api, params=parameter)

print(f"Status Code: {response.status_code}")

hasil = response.json()

print(f"Jumlah TV ditemukan (total_results): {hasil['total_results']}")
print(f"Jumlah TV yang dikirim kali ini    : {len(hasil['results'])}")

Status Code: 200
Jumlah TV ditemukan (total_results): 20001
Jumlah TV yang dikirim kali ini    : 20

In [4]:
# Menampilkan hasil data yang didapat setelah permintaan melalui API 
hasil['total_results']
hasil['results']

[{'adult': False,
  'backdrop_path': '/uc1p1PEbEMpdIHqnU9TESNC6Jhp.jpg',
  'genre_ids': [18],
  'id': 275102,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '스캔들',
  'overview': 'In Joseon, a secret proposal ignites hidden desires in a gifted noblewoman, a famed lover and an unsuspecting lady caught in their dangerous game.',
  'popularity': 3400.2893,
  'poster_path': '/4TU0PcHBIl0wPW5B6aVRGExOnHE.jpg',
  'first_air_date': '2026-09-18',
  'softcore': False,
  'name': 'The Scandal',
  'vote_average': 6.273,
  'vote_count': 11},
 {'adult': False,
  'backdrop_path': '/pF0qkRsrHkdYadPWY9AMeFZfcwk.jpg',
  'genre_ids': [10759, 80],
  'id': 108978,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Reacher',
  'overview': 'Jack Reacher, a veteran military police investigator, has just recently entered civilian life. Reacher is a drifter, carrying no phone and the barest of essentials as he travels the country and explores the nation he once served.',
  'popularity': 867.0873,
  'poster_path': '/f1VCQIG2iCyOookdgOzwtUpwWC0.jpg',
  'first_air_date': '2022-02-03',
  'softcore': False,
  'name': 'Reacher',
  'vote_average': 8.1,
  'vote_count': 3383},
 {'adult': False,
  'backdrop_path': '/qFfWFwfaEHzDLWLuttWiYq7Poy2.jpg',
  'genre_ids': [10767],
  'id': 2261,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'The Tonight Show Starring Johnny Carson',
  'overview': "The Tonight Show Starring Johnny Carson is a talk show hosted by Johnny Carson under The Tonight Show franchise from 1962 to 1992. It originally aired during late-night. For its first ten years, Carson's Tonight Show was based in New York City with occasional trips to Burbank, California; in May 1972, the show moved permanently to Burbank, California. In 2002, The Tonight Show Starring Johnny Carson was ranked #12 on TV Guide's 50 Greatest TV Shows of All Time.",
  'popularity': 809.6015,
  'poster_path': '/uSvET5YUvHNDIeoCpErrbSmasFb.jpg',
  'first_air_date': '1962-10-01',
  'softcore': False,
  'name': 'The Tonight Show Starring Johnny Carson',
  'vote_average': 7.536,
  'vote_count': 96},
 {'adult': False,
  'backdrop_path': '/gMMnf8VRg3Z98WaFmOLr9Jk8pIs.jpg',
  'genre_ids': [35, 10767],
  'id': 63770,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'The Late Show with Stephen Colbert',
  'overview': 'Stephen Colbert brings his signature satire and comedy to The Late Show with Stephen Colbert, the #1 show in late night, where he talks with an eclectic mix of guests about what is new and relevant in the worlds of politics, entertainment, business, music, technology, and more. Featuring bandleader Jon Batiste with his band Stay Human, the Emmy Award-nominated show is broadcast from the historic Ed Sullivan Theater.',
  'popularity': 709.1087,
  'poster_path': '/9jkThAGYj2yp8jsS6Nriy5mzKFT.jpg',
  'first_air_date': '2015-09-08',
  'softcore': False,
  'name': 'The Late Show with Stephen Colbert',
  'vote_average': 6.082,
  'vote_count': 364},
 {'adult': False,
  'backdrop_path': '/hINekSpbcBxjnjGqmIm6I4bz2ab.jpg',
  'genre_ids': [10767, 35],
  'id': 22980,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Watch What Happens Live with Andy Cohen',
  'overview': 'Bravo network executive Andy Cohen discusses pop culture topics with celebrities and reality show personalities.',
  'popularity': 676.0239,
  'poster_path': '/onSD9UXfJwrMXWhq7UY7hGF2S1h.jpg',
  'first_air_date': '2009-07-16',
  'softcore': False,
  'name': 'Watch What Happens Live with Andy Cohen',
  'vote_average': 4.969,
  'vote_count': 96},
 {'adult': False,
  'backdrop_path': '/tc7canPSAn2X14hYi6Rl3gZm1o4.jpg',
  'genre_ids': [80, 18],
  'id': 549,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Law & Order',
  'overview': "In cases ripped from the headlines, police investigate serious and often deadly crimes, weighing the evidence and questioning the suspects until someone is taken into custody. The district attorney's office then builds a case to convict the perpetrator by proving the person guilty beyond a reasonable doubt. Working together, these expert teams navigate all sides of the complex criminal justice system to make New York a safer place.",
  'popularity': 565.5337,
  'poster_path': '/haJ9eHytVO3H3JooMJG1DiWwDNm.jpg',
  'first_air_date': '1990-09-13',
  'softcore': False,
  'name': 'Law & Order',
  'vote_average': 7.286,
  'vote_count': 726},
 {'adult': False,
  'backdrop_path': '/mU7l9UaEItxHbg2YBNs0sHjoFVY.jpg',
  'genre_ids': [18, 10768],
  'id': 113962,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Lioness',
  'overview': "Cruz Manuelos, a rough-around-the-edges but passionate young Marine, is recruited to join the CIA's Lioness Engagement Team to help bring down a terrorist organization from within. Joe, the station chief of the Lioness program, is tasked with training, managing and leading her female undercover operatives.",
  'popularity': 568.1133,
  'poster_path': '/rzpHPSEgPTpRs8EHbygwsOw7jC0.jpg',
  'first_air_date': '2023-07-23',
  'softcore': False,
  'name': 'Lioness',
  'vote_average': 8.2,
  'vote_count': 1592},
 {'adult': False,
  'backdrop_path': '/amtOltTVcK9vQtL1iQS6p3LBi05.jpg',
  'genre_ids': [10767],
  'id': 62223,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'The Late Late Show with James Corden',
  'overview': "Once Craig Ferguson retires, James Corden will be taking over The Late Late Show. The show is a late night talk show that interviews celebrities and has its own bits. And of course, it's all hosted by James Corden.",
  'popularity': 465.2712,
  'poster_path': '/qPmVoG8G9tc1nN8ZwGV2zYcknit.jpg',
  'first_air_date': '2015-03-23',
  'softcore': False,
  'name': 'The Late Late Show with James Corden',
  'vote_average': 5.149,
  'vote_count': 148},
 {'adult': False,
  'backdrop_path': '/i4OYRb5V13BrOnTPJGdyXWg4r0J.jpg',
  'genre_ids': [35, 10767],
  'id': 59941,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'The Tonight Show Starring Jimmy Fallon',
  'overview': "After Jay Leno's second retirement from the program, Jimmy Fallon stepped in as his permanent replacement. After 42 years in Los Angeles the program was brought back to New York.",
  'popularity': 516.034,
  'poster_path': '/1N4o5PmmqhlVDrcdJ2RlCFWbLGX.jpg',
  'first_air_date': '2014-02-17',
  'softcore': False,
  'name': 'The Tonight Show Starring Jimmy Fallon',
  'vote_average': 5.756,
  'vote_count': 389},
 {'adult': False,
  'backdrop_path': '/jWXrQstj7p3Wl5MfYWY6IHqRpDb.jpg',
  'genre_ids': [10763],
  'id': 94722,
  'origin_country': ['DE'],
  'original_language': 'de',
  'original_name': 'Tagesschau',
  'overview': 'German daily news program, the oldest still existing program on German television.',
  'popularity': 461.7041,
  'poster_path': '/7dFZJ2ZJJdcmkp05B9NWlqTJ5tq.jpg',
  'first_air_date': '1952-12-26',
  'softcore': False,
  'name': 'Tagesschau',
  'vote_average': 6.768,
  'vote_count': 256},
 {'adult': False,
  'backdrop_path': '/dyFTt1a9ZpFdKE96kPlE9fQvXOJ.jpg',
  'genre_ids': [10751, 35, 18],
  'id': 91759,
  'origin_country': ['HK'],
  'original_language': 'cn',
  'original_name': '愛·回家之開心速遞',
  'overview': "Hung Sue Gan starting from the bottom, established his own logistics company, which is now running smoothly. His only concern now are his three daughters. His eldest daughter has immigrated overseas. His second daughter Hung Yeuk Shui has reached the marriageable age, but has no hopes for marriage anytime soon. She is constantly bickering with her younger sister Hung Sum Yue, who is an honour student, over trivial matters, causing their father to not know whether to laugh or cry. Hung Sue Yan, Hung Sue Gan's brother, moves in with the family, temporarily ending his life as a nomadic photographer. He joins Hung Yeuk Shui's company and encounters Ko Pak Fei, the director of an online shop. The two appear to be former lovers, making for lots of laughter. Since Hung Sue Yan moved in, a series of strange events have occurred in the family. Upon investigation, the source is traced to Lung Ging Fung, a promising young man who is the son of department store mogul Lung Gam Wai.",
  'popularity': 585.6953,
  'poster_path': '/lgD4j9gUGmMckZpWWRJjorWqGVT.jpg',
  'first_air_date': '2017-02-20',
  'softcore': False,
  'name': 'Come Home Love: Lo and Behold',
  'vote_average': 5.435,
  'vote_count': 46},
 {'adult': False,
  'backdrop_path': '/rJFqKcmMSttdNP58l0dVzY2NcTA.jpg',
  'genre_ids': [80, 18, 9648],
  'id': 5920,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'The Mentalist',
  'overview': 'Patrick Jane, a former celebrity psychic medium, uses his razor sharp skills of observation and expertise at "reading" people to solve serious crimes with the California Bureau of Investigation.',
  'popularity': 429.2205,
  'poster_path': '/acYXu4KaDj1NIkMgObnhe4C4a0T.jpg',
  'first_air_date': '2008-09-23',
  'softcore': False,
  'name': 'The Mentalist',
  'vote_average': 8.407,
  'vote_count': 4746},
 {'adult': False,
  'backdrop_path': '/obtdxPgmfykYwVnvuYXC5f2xKlQ.jpg',
  'genre_ids': [80, 18, 9648],
  'id': 2734,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Law & Order: Special Victims Unit',
  'overview': 'In the criminal justice system, sexually-based offenses are considered especially heinous. In New York City, the dedicated detectives who investigate these vicious felonies are members of an elite squad known as the Special Victims Unit. These are their stories.',
  'popularity': 459.9573,
  'poster_path': '/iofokHZoUB4Qhik4PflvJl8TT6a.jpg',
  'first_air_date': '1999-09-20',
  'softcore': False,
  'name': 'Law & Order: Special Victims Unit',
  'vote_average': 7.959,
  'vote_count': 4357},
 {'adult': False,
  'backdrop_path': '/dfX2UaHVE5c7kLBFbgmEZJuy4Ev.jpg',
  'genre_ids': [10767, 35],
  'id': 61818,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Late Night with Seth Meyers',
  'overview': 'Seth Meyers, who is "Saturday Night Live\'s" longest serving anchor on the show\'s wildly popular "Weekend Update," takes over as host of NBC\'s "Late Night" — home to A-list celebrity guests, memorable comedy and the best in musical talent. As the Emmy Award-winning head writer for "SNL," Meyers has established a reputation for sharp wit and perfectly timed comedy, and has gained fame for his spot-on jokes and satire. Meyers takes his departure from "SNL" to his new post at "Late Night," as Jimmy Fallon moves to "The Tonight Show".',
  'popularity': 394.2658,
  'poster_path': '/u8VruEGv7mtyJihVn2CSA1u90pk.jpg',
  'first_air_date': '2014-02-25',
  'softcore': False,
  'name': 'Late Night with Seth Meyers',
  'vote_average': 5.112,
  'vote_count': 134},
 {'adult': False,
  'backdrop_path': '/iixxhk3ycXmFqBn616pAsC3lu53.jpg',
  'genre_ids': [16, 35],
  'id': 1433,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'American Dad!',
  'overview': 'The series focuses on an eccentric motley crew that is the Smith family and their three housemates: Father, husband, and breadwinner Stan Smith; his better half housewife, Francine Smith; their college-aged daughter, Hayley Smith; and their high-school-aged son, Steve Smith. Outside of the Smith family, there are three additional main characters, including Hayley\'s boyfriend turned husband, Jeff Fischer; the family\'s man-in-a-goldfish-body pet, Klaus; and most notably the family\'s zany alien, Roger, who is "full of masquerades, brazenness, and shocking antics."',
  'popularity': 413.133,
  'poster_path': '/eb9sH2am9IUSQ8GhXTNAVoujk8W.jpg',
  'first_air_date': '2005-02-06',
  'softcore': False,
  'name': 'American Dad!',
  'vote_average': 7.019,
  'vote_count': 2451},
 {'adult': False,
  'backdrop_path': '/ncQ8D4j8GSuL9CzncLEXnhHDxHy.jpg',
  'genre_ids': [16, 35],
  'id': 456,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'The Simpsons',
  'overview': 'Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.',
  'popularity': 411.3515,
  'poster_path': '/uWpG7GqfKGQqX4YMAo3nv5OrglV.jpg',
  'first_air_date': '1989-12-17',
  'softcore': False,
  'name': 'The Simpsons',
  'vote_average': 8.0,
  'vote_count': 11024},
 {'adult': False,
  'backdrop_path': '/l7wShoIdIUwaDIbsHno9pO5MZXT.jpg',
  'genre_ids': [16, 35],
  'id': 1434,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Family Guy',
  'overview': "Sick, twisted, politically incorrect and Freakin' Sweet animated series featuring the adventures of the dysfunctional Griffin family. Bumbling Peter and long-suffering Lois have three kids. Stewie (a brilliant but sadistic baby bent on killing his mother and taking over the world), Meg (the oldest, and is the most unpopular girl in town) and Chris (the middle kid, he's not very bright but has a passion for movies). The final member of the family is Brian - a talking dog and much more than a pet, he keeps Stewie in check whilst sipping Martinis and sorting through his own life issues.",
  'popularity': 390.2893,
  'poster_path': '/3PFsEuAiyLkWsP4GG6dIV37Q6gu.jpg',
  'first_air_date': '1999-01-31',
  'softcore': False,
  'name': 'Family Guy',
  'vote_average': 7.411,
  'vote_count': 5121},
 {'adult': False,
  'backdrop_path': '/kCd0rmnNwCd3sgupO9DqSi9aHa0.jpg',
  'genre_ids': [10767],
  'id': 65270,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '라디오스타',
  'overview': '“Radio Star” is a South Korean music talk show where the guests and hosts talk openly and intimately about their lives, their pasts and their work. It is part of Munhwa Broadcasting Corporation\'s "Golden Fishery" programming block.',
  'popularity': 309.5015,
  'poster_path': '/uRUZDsvUfIP3JUEgOC8ReBlQQUU.jpg',
  'first_air_date': '2007-05-30',
  'softcore': False,
  'name': 'Radio Star',
  'vote_average': 5.5,
  'vote_count': 6},
 {'adult': False,
  'backdrop_path': '/c1aBrG5s5xFa6Tbnihu2Hhj4t2q.jpg',
  'genre_ids': [80, 18, 10759],
  'id': 4614,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'NCIS',
  'overview': 'From murder and espionage to terrorism and stolen submarines, a team of special agents investigates any crime that has any connection to Navy and Marine Corps personnel, regardless of rank or position.',
  'popularity': 377.2471,
  'poster_path': '/mBcu8d6x6zB1el3MPNl7cZQEQ31.jpg',
  'first_air_date': '2003-09-23',
  'softcore': False,
  'name': 'NCIS',
  'vote_average': 7.6,
  'vote_count': 2572},
 {'adult': False,
  'backdrop_path': '/a8a8z4aJr40zYgRMfmSESppX2eO.jpg',
  'genre_ids': [10764, 35],
  'id': 70672,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '아는 형님',
  'overview': 'Male celebs play make-believe as high schoolers, welcoming star transfer students every week and engaging in battles of witty humor and slapstick.',
  'popularity': 302.2832,
  'poster_path': '/2jIi55JtYKJTL1km8qHMuUilOWo.jpg',
  'first_air_date': '2015-12-05',
  'softcore': False,
  'name': 'Men on a Mission',
  'vote_average': 7.4,
  'vote_count': 42}]

In [5]:
# Melakukan inisialiasai pada hasil dan menapilkan data pada index 0 atau raw pertama 
tv = hasil["results"][0]
tv

{'adult': False,
 'backdrop_path': '/uc1p1PEbEMpdIHqnU9TESNC6Jhp.jpg',
 'genre_ids': [18],
 'id': 275102,
 'origin_country': ['KR'],
 'original_language': 'ko',
 'original_name': '스캔들',
 'overview': 'In Joseon, a secret proposal ignites hidden desires in a gifted noblewoman, a famed lover and an unsuspecting lady caught in their dangerous game.',
 'popularity': 3400.2893,
 'poster_path': '/4TU0PcHBIl0wPW5B6aVRGExOnHE.jpg',
 'first_air_date': '2026-09-18',
 'softcore': False,
 'name': 'The Scandal',
 'vote_average': 6.273,
 'vote_count': 11}

In [6]:
# Preview pada data yang telah diload, kemudian hanya menapilkan data yang berisi nama, overview, dan tanggal
print("Nama Serial :", tv["name"])
print("Overview    :", tv["overview"])
print("Tanggal     :", tv["first_air_date"])

Nama Serial : The Scandal
Overview    : In Joseon, a secret proposal ignites hidden desires in a gifted noblewoman, a famed lover and an unsuspecting lady caught in their dangerous game.
Tanggal     : 2026-09-18

## **Tahap 3: Mengubah ke dalam bentuk Class**


Pada tahap ini, kita akan menerapkan konsep *Object-Oriented Programming (OOP)* dengan membungkus proses pengambilan data dari TMDB API ke dalam sebuah class.

Sebelumnya, proses pengambilan data dilakukan secara langsung menggunakan requests. Dengan menggunakan class, proses tersebut dapat dibuat lebih terstruktur, terorganisir, dan dapat digunakan kembali tanpa harus menuliskan kode yang sama berulang kali.

In [7]:
### Membungkus dalam bentuk Class

class TMBDFavTV:

    def __init__(self, api_key):
        self.api_key = api_key
        self.alamat_base = "https://api.themoviedb.org/3"

    def get_tv_data(self, target_rows=1000):
        alamat_api = f"{self.alamat_base}/discover/tv"

        # Misalkan dalam satu halaman terdapat 20 data
        jumlah_halaman = (target_rows + 19) // 20
        all_tv = []

        for page in range(1, jumlah_halaman + 1):

            params = {
                "api_key": self.api_key,
                "language": "en-US",
                "page": page,
                "sort_by": "popularity.desc"
            }

            try:
                response = requests.get(alamat_api, params=params)
                print(f"Page {page} | Status Code: {response.status_code}")

                if response.status_code == 200:
                    data = response.json()
                    all_tv.extend(data["results"])
                else:
                    print("Error:", response.text)
                    break

            except requests.exceptions.RequestException as e:
                print(f"Terjadi kesalahan koneksi pada page {page}: {e}")
                break

        # Mengubah hasil pengambilan data menjadi DataFrame
        df = pd.DataFrame(all_tv)

        print(f"\nTotal data terkumpul: {len(df)}")

        return df

In [8]:
# Membuat objek tmbd dari class TMBDFavTV
tmbd = TMBDFavTV(API_KEY)
# Memanggil dan menyimpan data 
df = tmbd.get_tv_data(1000)

Page 1 | Status Code: 200
Page 2 | Status Code: 200
Page 3 | Status Code: 200
Page 4 | Status Code: 200
Page 5 | Status Code: 200
Page 6 | Status Code: 200
Page 7 | Status Code: 200
Page 8 | Status Code: 200
Page 9 | Status Code: 200
Page 10 | Status Code: 200
Page 11 | Status Code: 200
Page 12 | Status Code: 200
Page 13 | Status Code: 200
Page 14 | Status Code: 200
Page 15 | Status Code: 200
Page 16 | Status Code: 200
Page 17 | Status Code: 200
Page 18 | Status Code: 200
Page 19 | Status Code: 200
Page 20 | Status Code: 200
Page 21 | Status Code: 200
Page 22 | Status Code: 200
Page 23 | Status Code: 200
Page 24 | Status Code: 200
Page 25 | Status Code: 200
Page 26 | Status Code: 200
Page 27 | Status Code: 200
Page 28 | Status Code: 200
Page 29 | Status Code: 200
Page 30 | Status Code: 200
Page 31 | Status Code: 200
Page 32 | Status Code: 200
Page 33 | Status Code: 200
Page 34 | Status Code: 200
Page 35 | Status Code: 200
Page 36 | Status Code: 200
Page 37 | Status Code: 200
Page 38 | Status Code: 200
Page 39 | Status Code: 200
Page 40 | Status Code: 200
Page 41 | Status Code: 200
Page 42 | Status Code: 200
Page 43 | Status Code: 200
Page 44 | Status Code: 200
Page 45 | Status Code: 200
Page 46 | Status Code: 200
Page 47 | Status Code: 200
Page 48 | Status Code: 200
Page 49 | Status Code: 200
Page 50 | Status Code: 200

Total data terkumpul: 1000

In [22]:
# Menampilkan data dengan memperlihatkan 10 data pertama paling atas
df.head(3)

,adult,backdrop_path,genre_ids,id,origin_country,original_language,original_name,overview,popularity,poster_path,first_air_date,softcore,name,vote_average,vote_count
0,False,/uc1p1PEbEMpdIHqnU9TESNC6Jhp.jpg,[18],275102,[KR],ko,스캔들,"In Joseon, a secret proposal ignites hidden de...",3400.2893,/4TU0PcHBIl0wPW5B6aVRGExOnHE.jpg,2026-09-18,False,The Scandal,6.273,11
1,False,/pF0qkRsrHkdYadPWY9AMeFZfcwk.jpg,"[10759, 80]",108978,[US],en,Reacher,"Jack Reacher, a veteran military police invest...",867.0873,/f1VCQIG2iCyOookdgOzwtUpwWC0.jpg,2022-02-03,False,Reacher,8.100,3383
2,False,/qFfWFwfaEHzDLWLuttWiYq7Poy2.jpg,[10767],2261,[US],en,The Tonight Show Starring Johnny Carson,The Tonight Show Starring Johnny Carson is a t...,809.6015,/uSvET5YUvHNDIeoCpErrbSmasFb.jpg,1962-10-01,False,The Tonight Show Starring Johnny Carson,7.536,96

In [10]:
# Melihat informasi data 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              1000 non-null   bool
 1   backdrop_path      959 non-null    str
 2   genre_ids          1000 non-null   object
 3   id                 1000 non-null   int64
 4   origin_country     1000 non-null   object
 5   original_language  1000 non-null   str
 6   original_name      1000 non-null   str
 7   overview           1000 non-null   str
 8   popularity         1000 non-null   float64
 9   poster_path        986 non-null    str
 10  first_air_date     1000 non-null   str
 11  softcore           1000 non-null   bool
 12  name               1000 non-null   str
 13  vote_average       1000 non-null   float64
 14  vote_count         1000 non-null   int64
dtypes: bool(2), float64(2), int64(2), object(2), str(7)
memory usage: 103.6+ KB

Berdasarkan hasil informasi data di atas, dapat dilihat bahwa setiap kolom memiliki tipe data yang berbeda. Selanjutnya, perlu diperiksa apakah tipe data yang digunakan pada setiap kolom sudah sesuai dengan karakteristik datanya. Pada kolom first_air_date, tipe data yang digunakan masih berupa str. Hal ini kurang sesuai karena kolom tersebut berisi informasi berupa tanggal. Oleh karena itu, tipe data pada kolom **first_air_date** perlu diubah menjadi **datetime** agar dapat digunakan untuk analisis data berdasarkan waktu. Proses ini kita dapat lakukan pada tahap *Data Cleaning*.

## **Tahap 4: Membersihkan Data (Data Cleaning)**

Pada tahap ini kita diminta untuk melakukan pembersihan data dengan kriteria pengerjaan yang wajib dilakukan sebagai berikut :
1. Nilai yang kosong
2. Baris yang kembar
3. Tipe data yang tidak sesuai

In [21]:
print("1. Jumlah sel kosong per kolom:")
print(df.isnull().sum())

print("\n2. Jumlah baris yang kembar:")
print(df.duplicated(subset="id").sum())

print("\n3. Tipe data setiap kolom:")
print(df.dtypes)

1. Jumlah sel kosong per kolom:
adult                 0
backdrop_path        41
genre_ids             0
id                    0
origin_country        0
original_language     0
original_name         0
overview              0
popularity            0
poster_path          14
first_air_date        0
softcore              0
name                  0
vote_average          0
vote_count            0
dtype: int64

2. Jumlah baris yang kembar:
67

3. Tipe data setiap kolom:
adult                   bool
backdrop_path            str
genre_ids             object
id                     int64
origin_country        object
original_language        str
original_name            str
overview                 str
popularity           float64
poster_path              str
first_air_date           str
softcore                bool
name                     str
vote_average         float64
vote_count             int64
dtype: object

### **Membaca hasil pemeriksaan**

Berdasarkan hasil pemeriksaan data di atas, terdapat beberapa hal yang perlu diperhatikan sebelum data digunakan untuk tahap analisis.

Pertama, terdapat nilai kosong pada dua kolom, yaitu backdrop_path sebanyak 41 data dan poster_path sebanyak 14 data. Nilai kosong tersebut masih dapat dipertahankan karena kedua kolom tersebut hanya berisi informasi mengenai gambar latar dan poster serial TV. Oleh karena itu, nilai kosong akan diisi dengan keterangan "Tidak tersedia", sehingga baris data tidak perlu dihapus.

Kedua, terdapat 67 baris data yang terindikasi kembar berdasarkan kolom id. Kolom id digunakan sebagai acuan karena setiap serial TV pada TMDB memiliki identitas atau ID yang berbeda. Oleh karena itu, data yang memiliki id yang sama akan dianggap sebagai data yang sama dan salah satunya perlu dihapus.

Ketiga, berdasarkan hasil pemeriksaan tipe data, sebagian besar kolom telah memiliki tipe data yang sesuai. Kolom seperti id, popularity, vote_average, dan vote_count telah menggunakan tipe data numerik, sedangkan kolom seperti adult dan softcore telah menggunakan tipe bool. Namun, kolom first_air_date masih bertipe str, padahal kolom tersebut berisi informasi tanggal. Oleh karena itu, kolom first_air_date perlu dikonversi menjadi tipe datetime agar dapat digunakan dengan tepat dalam analisis berdasarkan waktu.

### Menangani Nilai Kosong (Missing Value)

In [23]:
def bersihkan_path(teks):
    if pd.isna(teks):
        return "Tidak tersedia"
    return teks


df["backdrop_path"] = df["backdrop_path"].apply(bersihkan_path)
df["poster_path"] = df["poster_path"].apply(bersihkan_path)

print("Sel kosong setelah ditangani:")
print(df.isnull().sum())

Sel kosong setelah ditangani:
adult                0
backdrop_path        0
genre_ids            0
id                   0
origin_country       0
original_language    0
original_name        0
overview             0
popularity           0
poster_path          0
first_air_date       0
softcore             0
name                 0
vote_average         0
vote_count           0
dtype: int64

### Menangani Baris Kembar

In [24]:
jumlah_sebelum = len(df)

df_bersih = df.drop_duplicates(subset="id")

print(f"Jumlah baris sebelum : {jumlah_sebelum}")
print(f"Jumlah baris sesudah : {len(df_bersih)}")
print(f"Baris kembar dibuang : {jumlah_sebelum - len(df_bersih)}")

Jumlah baris sebelum : 1000
Jumlah baris sesudah : 933
Baris kembar dibuang : 67

### Menangani Tipe Data

In [34]:
def ubah_ke_tanggal(teks):
    return pd.to_datetime(teks)


print("Tipe data sebelum:", df_bersih["first_air_date"].dtype)

df_bersih["first_air_date"] = df_bersih["first_air_date"].apply(ubah_ke_tanggal)

print("Tipe data sesudah:", df_bersih["first_air_date"].dtype)

df_bersih.tail(10)

Tipe data sebelum: datetime64[us]
Tipe data sesudah: datetime64[us]

,adult,backdrop_path,genre_ids,id,origin_country,original_language,original_name,overview,popularity,poster_path,first_air_date,softcore,name,vote_average,vote_count
981,False,/fs5VXKvIUcfTn3nsc3g4s3OIcV4.jpg,[18],46880,[US],en,The Fosters,"Stef Foster, a dedicated police officer, and h...",47.4421,/iRCmazqaUNNsgZyR6tNDl88pXp3.jpg,2013-06-03,False,The Fosters,7.500,339
983,False,/a97Q8f3dWiaMg2nq79zG5oZVotp.jpg,"[10768, 35]",4068,[US],en,Hogan's Heroes,From a German prisoner of war camp during Worl...,47.4310,/qifpp3AmNx54Ko4obdwxOWNf0lo.jpg,1965-09-17,False,Hogan's Heroes,7.544,193
985,False,/qdVdWLUAj9Xxrx0OIT76gWVI4fg.jpg,[10764],2612,[US],en,Deadliest Catch,"Forty-foot waves, 700 pound crab pots, freezin...",47.3481,/aqF7wHfA2n89zbBqG6DLuDjrHut.jpg,2005-04-12,False,Deadliest Catch,7.243,179
987,False,/8rEKZ1PdiglSi0jTyookQtZaQOo.jpg,[99],113630,[FR],fr,Enquêtes criminelles,,47.3201,/eQNT1q6BNJt55IHk0sI1O5grUhE.jpg,2008-10-08,False,Enquêtes criminelles,8.000,1
990,False,/xIYUHL2KEYNMAsjFuUCQQZsH7D1.jpg,"[16, 35, 10762]",112527,[JP],ja,オバケのQ太郎,"Q-taro, a monster, is living with the Ohara fa...",47.2093,/acb9g0rlsFhy3LBPDvMF7Tso9Q0.jpg,1985-04-01,False,Obake no Q-tarō,8.000,3
993,False,/bVml4IQKIS5DfPqgDoaZoRLlxIY.jpg,"[16, 10751, 10762, 35, 10759]",64783,[US],en,Dawn of the Croods,The world's first family is back for more laug...,47.1301,/cyCAsMLGECvEAFDfKcxcWy7YTOW.jpg,2015-12-24,False,Dawn of the Croods,7.440,100
994,False,/mP0LywGWY77Qa9rmfWZPJDEGaY2.jpg,"[18, 10751, 35, 10759, 10766]",86310,[IN],hi,राधाकृष्ण,The story of Radha and Krishna is the epitome ...,47.0688,/3SiMmfY0663JmjpAfftmj1h6XGP.jpg,2018-10-01,False,RadhaKrishn,9.000,4
995,False,/iohe4KtMpFKYzuA3QIBRrcbJIbz.jpg,"[16, 35, 10762]",3611,[US],en,Cow and Chicken,"Follows the surreal adventures of a cow, named...",47.0546,/1vsIbN9FOsr97vIAGLYpRu7ZiSq.jpg,1997-09-16,False,Cow and Chicken,7.082,536
997,False,/32kAbClMKp2BmwNPH5j8OKzyYt9.jpg,"[18, 80]",40758,[DE],de,Großstadtrevier,Follow the everyday work of a fictional police...,47.0132,/fVsntDN3mQAuaDFGiJTKar7fRcu.jpg,1986-12-16,False,Großstadtrevier,6.000,14
998,False,/bcdbAtYOHoE2KDXjgmWxWgSJ1gP.jpg,[10767],90648,[DE],de,ZDF-Fernsehgarten,,47.0022,/kUnK5nohn8YSoG4yMWGvEKCYSuM.jpg,1986-06-29,False,ZDF-Fernsehgarten,2.800,5

In [28]:
# Mengecek kembali perubahan tipe data melalui .info()
df_bersih.info()

<class 'pandas.DataFrame'>
Index: 933 entries, 0 to 998
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              933 non-null    bool
 1   backdrop_path      933 non-null    str
 2   genre_ids          933 non-null    object
 3   id                 933 non-null    int64
 4   origin_country     933 non-null    object
 5   original_language  933 non-null    str
 6   original_name      933 non-null    str
 7   overview           933 non-null    str
 8   popularity         933 non-null    float64
 9   poster_path        933 non-null    str
 10  first_air_date     932 non-null    datetime64[us]
 11  softcore           933 non-null    bool
 12  name               933 non-null    str
 13  vote_average       933 non-null    float64
 14  vote_count         933 non-null    int64
dtypes: bool(2), datetime64[us](1), float64(2), int64(2), object(2), str(6)
memory usage: 103.9+ KB

In [31]:
display(
    df_bersih[
        [
            "id",
            "name",
            "first_air_date",
            "popularity",
            "vote_average",
            "vote_count"
        ]
    ].head(10)
)

,id,name,first_air_date,popularity,vote_average,vote_count
0,275102,The Scandal,2026-09-18,3400.2893,6.273,11
1,108978,Reacher,2022-02-03,867.0873,8.100,3383
2,2261,The Tonight Show Starring Johnny Carson,1962-10-01,809.6015,7.536,96
3,63770,The Late Show with Stephen Colbert,2015-09-08,709.1087,6.082,364
4,22980,Watch What Happens Live with Andy Cohen,2009-07-16,676.0239,4.969,96
5,549,Law & Order,1990-09-13,565.5337,7.286,726
6,113962,Lioness,2023-07-23,568.1133,8.200,1592
7,62223,The Late Late Show with James Corden,2015-03-23,465.2712,5.149,148
8,59941,The Tonight Show Starring Jimmy Fallon,2014-02-17,516.0340,5.756,389
9,94722,Tagesschau,1952-12-26,461.7041,6.768,256

## **Tahap 5: Menyimpan Hasil**

Pada tahap ini kita akan menyimpan data hasil cleaning ke dalam bentik .csv

In [35]:
df_bersih.to_csv("dataset_favTV.csv", index=False)
print("Data berhasil disimpan ke file: dataset_favTV.csv")

df_cek = pd.read_csv("dataset_favTV.csv")
print(f"File terbaca kembali: {len(df_cek)} baris, {len(df_cek.columns)} kolom")
df_cek.head()

Data berhasil disimpan ke file: dataset_favTV.csv
File terbaca kembali: 933 baris, 15 kolom

,adult,backdrop_path,genre_ids,id,origin_country,original_language,original_name,overview,popularity,poster_path,first_air_date,softcore,name,vote_average,vote_count
0,False,/uc1p1PEbEMpdIHqnU9TESNC6Jhp.jpg,[18],275102,['KR'],ko,스캔들,"In Joseon, a secret proposal ignites hidden de...",3400.2893,/4TU0PcHBIl0wPW5B6aVRGExOnHE.jpg,2026-09-18,False,The Scandal,6.273,11
1,False,/pF0qkRsrHkdYadPWY9AMeFZfcwk.jpg,"[10759, 80]",108978,['US'],en,Reacher,"Jack Reacher, a veteran military police invest...",867.0873,/f1VCQIG2iCyOookdgOzwtUpwWC0.jpg,2022-02-03,False,Reacher,8.100,3383
2,False,/qFfWFwfaEHzDLWLuttWiYq7Poy2.jpg,[10767],2261,['US'],en,The Tonight Show Starring Johnny Carson,The Tonight Show Starring Johnny Carson is a t...,809.6015,/uSvET5YUvHNDIeoCpErrbSmasFb.jpg,1962-10-01,False,The Tonight Show Starring Johnny Carson,7.536,96
3,False,/gMMnf8VRg3Z98WaFmOLr9Jk8pIs.jpg,"[35, 10767]",63770,['US'],en,The Late Show with Stephen Colbert,Stephen Colbert brings his signature satire an...,709.1087,/9jkThAGYj2yp8jsS6Nriy5mzKFT.jpg,2015-09-08,False,The Late Show with Stephen Colbert,6.082,364
4,False,/hINekSpbcBxjnjGqmIm6I4bz2ab.jpg,"[10767, 35]",22980,['US'],en,Watch What Happens Live with Andy Cohen,Bravo network executive Andy Cohen discusses p...,676.0239,/onSD9UXfJwrMXWhq7UY7hGF2S1h.jpg,2009-07-16,False,Watch What Happens Live with Andy Cohen,4.969,96

## **Tahap 6 :  Bahan untuk Slide**

In [36]:
print("=" * 50)

print("ANGKA UNTUK SLIDE")

print("=" * 50)

print(f"Sumber data              : The Movie Database (TMDB)")
print(f"Jenis data               : Serial TV")
print(f"Jumlah target data       : 1000")

print()

print(f"Baris sebelum dibersihkan : {jumlah_sebelum}")
print(f"Baris dataset akhir       : {len(df_bersih)}")

print()

print("Class yang dibuat:")

print("  1. TMBDFavTV - mengambil data serial TV dari TMDB API")

print()

print("Function yang dibuat:")

print("  1. bersihkan_path - menangani nilai kosong pada path gambar")
print("  2. ubah_ke_tanggal - mengubah teks tanggal menjadi tipe datetime")

print()

print("Temuan dari pembersihan data:")

print(f"  Nilai kosong backdrop_path : 41")
print(f"  Nilai kosong poster_path   : 14")
print(f"  Baris kembar dibuang       : {jumlah_sebelum - len(df_bersih)}")
print(f"  first_air_date             : str → datetime")

print("=" * 50)

==================================================
ANGKA UNTUK SLIDE
==================================================
Sumber data              : The Movie Database (TMDB)
Jenis data               : Serial TV
Jumlah target data       : 1000

Baris sebelum dibersihkan : 1000
Baris dataset akhir       : 933

Class yang dibuat:
  1. TMBDFavTV - mengambil data serial TV dari TMDB API

Function yang dibuat:
  1. bersihkan_path - menangani nilai kosong pada path gambar
  2. ubah_ke_tanggal - mengubah teks tanggal menjadi tipe datetime

Temuan dari pembersihan data:
  Nilai kosong backdrop_path : 41
  Nilai kosong poster_path   : 14
  Baris kembar dibuang       : 67
  first_air_date             : str → datetime
==================================================